### ISSUE TITLE
Clarification on setting default size for custom versions

### ISSUE THREAD

**Issue by mischacolley** [johnkoht/responsive-images#10]
Great work on this. Does exactly what I need. I'm having one issue though.

I'm wondering if you can define a default size when using custom versions?  Is it possible? My custom versions are overwriting the default versions fine except the default size is loading on initial page load before the JS switches it out. 

I was a bit unsure about the Mobvious instructions so perhaps I'm having this issue because I haven't set that part up correctly?

**Comment by johnkoht** [comment]
Hi @mischacolley there's not way right now. We've discussed refactoring a bit to handle that but nothing has been developed now. I'll let you know if anything changes.
