### ISSUE TITLE
Can't get the image to be responsive (config issue I think)

### ISSUE THREAD

**Issue by musixite** [johnkoht/responsive-images#4]
Hi John,

Thanks for your plugin, it will eventually make my life easier :)

However right now, I can't figure it out to make the images responsive.

Here's where I'm at, following your documentation without adding any customization.

Model: Page
Image field: cover
I'm using Bootstrap 3.

I get the error "undefined method `mobile'" with the following tag
```
<%= responsive_image_tag @page.cover.url %>
```

However, I can see the proper tag in the source when using this (no url):
```
<%= responsive_image_tag @page.cover %>
```

In the source:
```
<img alt="Cover" data-desktop-src="/uploads/page/cover/1/desktop_cover.jpg" data-mobile-src="/uploads/page/cover/1/mobile_cover.jpg" data-tablet-src="/uploads/page/cover/1/tablet_cover.jpg" src="/uploads/page/cover/1/cover.jpg">
```

The javascript responsive-images is loaded (after jQuery) with the following init:
```
<script type="text/javascript">
		$().ready(function() {
			$('img.responsive').responsive_images({
			  mobile_size: 480,
			  tablet_size: 768,
			  desktop_size: 992
			});
		});
	</script>
```

My initializer is the default (I did restart the server)
```
ResponsiveImages.configure do |config|
  # Set the default version for image. If you leave it at :default then it will use
  # the original size, i.e., image.url or you can use a specific version
  config.default = :default  
  # Add some custom sizes that you'll generate with Carrierwave. You can make as many
  # as you want. But you'll need to configure mobvious for any custom ones.
  config.sizes = {
    mobile: :mobile,            # carrierwave version size
    tablet: :tablet,            # another carrierwave version size
    desktop: :desktop           # and one more version...
  }
end
```

And my uploader class (it works when using the form to upload the image with CarrierWave):
```
process :resize_to_fill => [1200, 675]

version :desktop do
    process :resize_to_fill => [992,558]
  end

  version :tablet, :from_version => :desktop do
    process :resize_to_fill => [768,432]
  end

  version :mobile, :from_version => :desktop do
    process :resize_to_fill => [480,270]
  end

  version :thumb, :from_version => :desktop do
    process :resize_to_fill => [240,135]
  end
```

I'm stuck here. When I try to resize my browser (or refresh it after resizing), all the images are loaded but they don't load the proper one (only the default one shows up).

What am I missing?!

Thanks :)
- Vincent

**Comment by johnkoht** [comment]
Closing since I haven't heard back.
