### ISSUE TITLE
Update documentation to explicitly mention that class name should be part of responsive_image_tag

### ISSUE THREAD

**Issue by jrpolidario** [johnkoht/responsive-images#8]
My setup: 
ruby 2.1.2p95, rails 4.2.0, responsive_images 0.1.2

```ruby
// setup our responsive images
$('img.responsive').responsive_images({
  mobile_size: 480,
  tablet_size: 768,
  desktop_size: 980,
});
```

From the above documentation snippet, I think it is better to explicitly tell the readers that `.responsive` is a class name that should be included in the `responsive_image_tag` like the following working code of mine:

```ruby
<%= responsive_image_tag @post.image, class: 'responsive' %>
```

This I say, because I initially assumed that the class name 'responsive' is going to be automatically rendered in the HTML-generated code of responsive_image_tag, as the example:

```ruby
# basic usage
= responsive_image_tag @post.image.url
# => <img src="path/to/image.jpg", data-desktop-src="path/to/desktop_image.jpg" data-tablet-src="path/to/tablet_image.jpg" data-mobile-src="path/to/mobile_image.jpg" /> 
````

... doesn't say anything about including this class name, and that it should work as expected already. But, from my encounter on this problem, I found out that I would still need to explicitly add 'responsive' in the class name to finally make the images responsive.

I hope this at least helps some readers out there.

**Comment by johnkoht** [comment]
Hey @ jrpolidario thanks for pointing that out, I think that's a good idea. Would you be up to send a PR for the updated readme?
